export const tickers = [
  { symbol: "MMM", name: "3M" },
  { symbol: "AOS", name: "A. O. Smith" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "ACN", name: "Accenture" },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "AMD", name: "Advanced Micro Devices" },
  { symbol: "AES", name: "AES Corporation" },
  { symbol: "AFL", name: "Aflac" },
  { symbol: "A", name: "Agilent Technologies" },
  { symbol: "APD", name: "Air Products" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "AKAM", name: "Akamai Technologies" },
  { symbol: "ALB", name: "Albemarle Corporation" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities" },
  { symbol: "ALGN", name: "Align Technology" },
  { symbol: "ALLE", name: "Allegion" },
  { symbol: "LNT", name: "Alliant Energy" },
  { symbol: "ALL", name: "Allstate" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "MO", name: "Altria" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "AMCR", name: "Amcor" },
  { symbol: "AMTM", name: "Amentum" },
  { symbol: "AEE", name: "Ameren" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "AMT", name: "American Tower" },
  { symbol: "AWK", name: "American Water Works" },
  { symbol: "AMP", name: "Ameriprise Financial" },
  { symbol: "AME", name: "Ametek" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "APH", name: "Amphenol" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "ANSS", name: "Ansys" },
  { symbol: "AON", name: "Aon" },
  { symbol: "APA", name: "APA Corporation" },
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "APTV", name: "Aptiv" },
  { symbol: "ACGL", name: "Arch Capital Group" },
  { symbol: "ADM", name: "Archer Daniels Midland" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "AIZ", name: "Assurant" },
  { symbol: "T", name: "AT&T" },
  { symbol: "ATO", name: "Atmos Energy" },
  { symbol: "ADSK", name: "Autodesk" },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "AZO", name: "AutoZone" },
  { symbol: "AVB", name: "AvalonBay Communities" },
  { symbol: "AVY", name: "Avery Dennison" },
  { symbol: "AXON", name: "Axon Enterprise" },
  { symbol: "BKR", name: "Baker Hughes" },
  { symbol: "BALL", name: "Ball Corporation" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "BAX", name: "Baxter International" },
  { symbol: "BDX", name: "Becton Dickinson" },
  { symbol: "BRK-A", name: "Berkshire Hathaway" },
  { symbol: "BBY", name: "Best Buy" },
  { symbol: "TECH", name: "Bio-Techne" },
  { symbol: "BIIB", name: "Biogen" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "BX", name: "Blackstone Inc." },
  { symbol: "BK", name: "BNY Mellon" },
  { symbol: "BA", name: "The Boeing Company" },
  { symbol: "BKNG", name: "Booking Holdings" },
  { symbol: "BWA", name: "BorgWarner" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "BMY", name: "Bristol Myers Squibb" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "BR", name: "Broadridge Financial Solutions" },
  { symbol: "BRO", name: "Brown & Brown" },
  { symbol: "BF-B", name: "Brown–Forman" },
  { symbol: "BLDR", name: "Builders FirstSource" },
  { symbol: "BG", name: "Bunge Global" },
  { symbol: "BXP", name: "BXP, Inc." },
  { symbol: "CHRW", name: "C.H. Robinson" },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "CZR", name: "Caesars Entertainment" },
  { symbol: "CPT", name: "Camden Property Trust" },
  { symbol: "CPB", name: "Campbell Soup Company" },
  { symbol: "COF", name: "Capital One" },
  { symbol: "CAH", name: "Cardinal Health" },
  { symbol: "KMX", name: "CarMax" },
  { symbol: "CCL", name: "Carnival" },
  { symbol: "CARR", name: "Carrier Global" },
  { symbol: "CTLT", name: "Catalent" },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CBOE", name: "Cboe Global Markets" },
  { symbol: "CBRE", name: "CBRE Group" },
  { symbol: "CDW", name: "CDW" },
  { symbol: "CE", name: "Celanese" },
  { symbol: "COR", name: "Cencora" },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy" },
  { symbol: "CF", name: "CF Industries" },
  { symbol: "CRL", name: "Charles River Laboratories" },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CHD", name: "Church & Dwight" },
  { symbol: "CI", name: "Cigna" },
  { symbol: "CINF", name: "Cincinnati Financial" },
  { symbol: "CTAS", name: "Cintas" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "CFG", name: "Citizens Financial Group" },
  { symbol: "CLX", name: "Clorox" },
  { symbol: "CME", name: "CME Group" },
  { symbol: "CMS", name: "CMS Energy" },
  { symbol: "KO", name: "Coca-Cola Company (The)" },
  { symbol: "CTSH", name: "Cognizant" },
  { symbol: "CL", name: "Colgate-Palmolive" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "CAG", name: "Conagra Brands" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "ED", name: "Consolidated Edison" },
  { symbol: "STZ", name: "Constellation Brands" },
  { symbol: "CEG", name: "Constellation Energy" },
  { symbol: "COO", name: "Cooper Companies (The)" },
  { symbol: "CPRT", name: "Copart" },
  { symbol: "GLW", name: "Corning Inc." },
  { symbol: "CPAY", name: "Corpay" },
  { symbol: "CTVA", name: "Corteva" },
  { symbol: "CSGP", name: "CoStar Group" },
  { symbol: "COST", name: "Costco" },
  { symbol: "CTRA", name: "Coterra" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "CCI", name: "Crown Castle" },
  { symbol: "CSX", name: "CSX Corporation" },
  { symbol: "CMI", name: "Cummins" },
  { symbol: "CVS", name: "CVS Health" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "DRI", name: "Darden Restaurants" },
  { symbol: "DVA", name: "DaVita" },
  { symbol: "DAY", name: "Dayforce" },
  { symbol: "DECK", name: "Deckers Brands" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "DELL", name: "Dell Technologies" },
  { symbol: "DAL", name: "Delta Air Lines" },
  { symbol: "DVN", name: "Devon Energy" },
  { symbol: "DXCM", name: "Dexcom" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "DLR", name: "Digital Realty" },
  { symbol: "DFS", name: "Discover Financial" },
  { symbol: "DG", name: "Dollar General" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "D", name: "Dominion Energy" },
  { symbol: "DPZ", name: "Domino's" },
  { symbol: "DOV", name: "Dover Corporation" },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "DHI", name: "D. R. Horton" },
  { symbol: "DTE", name: "DTE Energy" },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "DD", name: "DuPont" },
  { symbol: "EMN", name: "Eastman Chemical Company" },
  { symbol: "ETN", name: "Eaton Corporation" },
  { symbol: "EBAY", name: "eBay" },
  { symbol: "ECL", name: "Ecolab" },
  { symbol: "EIX", name: "Edison International" },
  { symbol: "EW", name: "Edwards Lifesciences" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "EMR", name: "Emerson Electric" },
  { symbol: "ENPH", name: "Enphase Energy" },
  { symbol: "ETR", name: "Entergy" },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "EPAM", name: "EPAM Systems" },
  { symbol: "EQT", name: "EQT Corporation" },
  { symbol: "EFX", name: "Equifax" },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "ERIE", name: "Erie Indemnity" },
  { symbol: "ESS", name: "Essex Property Trust" },
  { symbol: "EL", name: "Estée Lauder Companies (The)" },
  { symbol: "EG", name: "Everest Group" },
  { symbol: "EVRG", name: "Evergy" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "EXC", name: "Exelon" },
  { symbol: "EXPE", name: "Expedia Group" },
  { symbol: "EXPD", name: "Expeditors International" },
  { symbol: "EXR", name: "Extra Space Storage" },
  { symbol: "XOM", name: "ExxonMobil" },
  { symbol: "FFIV", name: "F5, Inc." },
  { symbol: "FDS", name: "FactSet" },
  { symbol: "FICO", name: "Fair Isaac" },
  { symbol: "FAST", name: "Fastenal" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FDX", name: "FedEx" },
  { symbol: "FIS", name: "Fidelity National Information Services" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "FSLR", name: "First Solar" },
  { symbol: "FE", name: "FirstEnergy" },
  { symbol: "FI", name: "Fiserv" },
  { symbol: "FMC", name: "FMC Corporation" },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "FTV", name: "Fortive" },
  { symbol: "FOXA", name: "Fox Corporation (Class A)" },
  { symbol: "FOX", name: "Fox Corporation (Class B)" },
  { symbol: "BEN", name: "Franklin Resources" },
  { symbol: "FCX", name: "Freeport-McMoRan" },
  { symbol: "GRMN", name: "Garmin" },
  { symbol: "IT", name: "Gartner" },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "GEHC", name: "GE HealthCare" },
  { symbol: "GEV", name: "GE Vernova" },
  { symbol: "GEN", name: "Gen Digital" },
  { symbol: "GNRC", name: "Generac" },
  { symbol: "GD", name: "General Dynamics" },
  { symbol: "GIS", name: "General Mills" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "GPC", name: "Genuine Parts Company" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "GPN", name: "Global Payments" },
  { symbol: "GL", name: "Globe Life" },
  { symbol: "GDDY", name: "GoDaddy" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "HAL", name: "Halliburton" },
  { symbol: "HIG", name: "Hartford (The)" },
  { symbol: "HAS", name: "Hasbro" },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "DOC", name: "Healthpeak Properties" },
  { symbol: "HSIC", name: "Henry Schein" },
  { symbol: "HSY", name: "Hershey Company (The)" },
  { symbol: "HES", name: "Hess Corporation" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise" },
  { symbol: "HLT", name: "Hilton Worldwide" },
  { symbol: "HOLX", name: "Hologic" },
  { symbol: "HD", name: "Home Depot (The)" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "HRL", name: "Hormel Foods" },
  { symbol: "HST", name: "Host Hotels & Resorts" },
  { symbol: "HWM", name: "Howmet Aerospace" },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HUBB", name: "Hubbell Incorporated" },
  { symbol: "HUM", name: "Humana" },
  { symbol: "HBAN", name: "Huntington Bancshares" },
  { symbol: "HII", name: "Huntington Ingalls Industries" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IDXX", name: "Idexx Laboratories" },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "INCY", name: "Incyte" },
  { symbol: "IR", name: "Ingersoll Rand" },
  { symbol: "PODD", name: "Insulet Corporation" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "IFF", name: "International Flavors & Fragrances" },
  { symbol: "IP", name: "International Paper" },
  { symbol: "IPG", name: "Interpublic Group of Companies (The)" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "IVZ", name: "Invesco" },
  { symbol: "INVH", name: "Invitation Homes" },
  { symbol: "IQV", name: "IQVIA" },
  { symbol: "IRM", name: "Iron Mountain" },
  { symbol: "JBHT", name: "J.B. Hunt" },
  { symbol: "JBL", name: "Jabil" },
  { symbol: "JKHY", name: "Jack Henry & Associates" },
  { symbol: "J", name: "Jacobs Solutions" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JCI", name: "Johnson Controls" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "JNPR", name: "Juniper Networks" },
  { symbol: "K", name: "Kellanova" },
  { symbol: "KVUE", name: "Kenvue" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KEYS", name: "Keysight Technologies" },
  { symbol: "KMB", name: "Kimberly-Clark" },
  { symbol: "KIM", name: "Kimco Realty" },
  { symbol: "KMI", name: "Kinder Morgan" },
  { symbol: "KKR", name: "KKR" },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "KHC", name: "Kraft Heinz" },
  { symbol: "KR", name: "Kroger" },
  { symbol: "LHX", name: "L3Harris" },
  { symbol: "LH", name: "LabCorp" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "LW", name: "Lamb Weston" },
  { symbol: "LVS", name: "Las Vegas Sands" },
  { symbol: "LDOS", name: "Leidos" },
  { symbol: "LEN", name: "Lennar" },
  { symbol: "LLY", name: "Lilly (Eli)" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "LYV", name: "Live Nation Entertainment" },
  { symbol: "LKQ", name: "LKQ Corporation" },
  { symbol: "LMT", name: "Lockheed Martin" },
  { symbol: "L", name: "Loews Corporation" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "LULU", name: "Lululemon Athletica" },
  { symbol: "LYB", name: "LyondellBasell" },
  { symbol: "MTB", name: "M&T Bank" },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "MKTX", name: "MarketAxess" },
  { symbol: "MAR", name: "Marriott International" },
  { symbol: "MMC", name: "Marsh McLennan" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "MAS", name: "Masco" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "MTCH", name: "Match Group" },
  { symbol: "MKC", name: "McCormick & Company" },
  { symbol: "MCD", name: "McDonald\'s" },
  { symbol: "MCK", name: "McKesson Corporation" },
  { symbol: "MDT", name: "Medtronic" },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "MET", name: "MetLife" },
  { symbol: "MTD", name: "Mettler Toledo" },
  { symbol: "MGM", name: "MGM Resorts" },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "MAA", name: "Mid-America Apartment Communities" },
  { symbol: "MRNA", name: "Moderna" },
  { symbol: "MHK", name: "Mohawk Industries" },
  { symbol: "MOH", name: "Molina Healthcare" },
  { symbol: "TAP", name: "Molson Coors Beverage Company" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "MPWR", name: "Monolithic Power Systems" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "MCO", name: "Moody's Corporation" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MOS", name: "Mosaic Company (The)" },
  { symbol: "MSI", name: "Motorola Solutions" },
  { symbol: "MSCI", name: "MSCI" },
  { symbol: "NDAQ", name: "Nasdaq, Inc." },
  { symbol: "NTAP", name: "NetApp" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "NEM", name: "Newmont" },
  { symbol: "NWSA", name: "News Corp (Class A)" },
  { symbol: "NWS", name: "News Corp (Class B)" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "NKE", name: "Nike, Inc." },
  { symbol: "NI", name: "NiSource" },
  { symbol: "NDSN", name: "Nordson Corporation" },
  { symbol: "NSC", name: "Norfolk Southern Railway" },
  { symbol: "NTRS", name: "Northern Trust" },
  { symbol: "NOC", name: "Northrop Grumman" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
  { symbol: "NRG", name: "NRG Energy" },
  { symbol: "NUE", name: "Nucor" },
  { symbol: "NVDA", name: "Nvidia" },
  { symbol: "NVR", name: "NVR, Inc." },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "ORLY", name: "O'Reilly Auto Parts" },
  { symbol: "OXY", name: "Occidental Petroleum" },
  { symbol: "ODFL", name: "Old Dominion" },
  { symbol: "OMC", name: "Omnicom Group" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "OKE", name: "ONEOK" },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "OTIS", name: "Otis Worldwide" },
  { symbol: "PCAR", name: "Paccar" },
  { symbol: "PKG", name: "Packaging Corporation of America" },
  { symbol: "PLTR", name: "Palantir Technologies" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "PARA", name: "Paramount Global" },
  { symbol: "PH", name: "Parker Hannifin" },
  { symbol: "PAYX", name: "Paychex" },
  { symbol: "PAYC", name: "Paycom" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "PNR", name: "Pentair" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "PCG", name: "PG&E Corporation" },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "PNW", name: "Pinnacle West" },
  { symbol: "PNC", name: "PNC Financial Services" },
  { symbol: "POOL", name: "Pool Corporation" },
  { symbol: "PPG", name: "PPG Industries" },
  { symbol: "PPL", name: "PPL Corporation" },
  { symbol: "PFG", name: "Principal Financial Group" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "PGR", name: "Progressive Corporation" },
  { symbol: "PLD", name: "Prologis" },
  { symbol: "PRU", name: "Prudential Financial" },
  { symbol: "PEG", name: "Public Service Enterprise Group" },
  { symbol: "PTC", name: "PTC Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PHM", name: "PulteGroup" },
  { symbol: "QRVO", name: "Qorvo" },
  { symbol: "PWR", name: "Quanta Services" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "DGX", name: "Quest Diagnostics" },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "RJF", name: "Raymond James Financial" },
  { symbol: "RTX", name: "RTX Corporation" },
  { symbol: "O", name: "Realty Income" },
  { symbol: "REG", name: "Regency Centers" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "RF", name: "Regions Financial Corporation" },
  { symbol: "RSG", name: "Republic Services" },
  { symbol: "RMD", name: "ResMed" },
  { symbol: "RVTY", name: "Revvity" },
  { symbol: "ROK", name: "Rockwell Automation" },
  { symbol: "ROL", name: "Rollins, Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "RCL", name: "Royal Caribbean Group" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "SBAC", name: "SBA Communications" },
  { symbol: "SLB", name: "Schlumberger" },
  { symbol: "STX", name: "Seagate Technology" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "SPG", name: "Simon Property Group" },
  { symbol: "SWKS", name: "Skyworks Solutions" },
  { symbol: "SJM", name: "J.M. Smucker Company (The)" },
  { symbol: "SW", name: "Smurfit WestRock" },
  { symbol: "SNA", name: "Snap-on" },
  { symbol: "SOLV", name: "Solventum" },
  { symbol: "SO", name: "Southern Company" },
  { symbol: "LUV", name: "Southwest Airlines" },
  { symbol: "SWK", name: "Stanley Black & Decker" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "STT", name: "State Street Corporation" },
  { symbol: "STLD", name: "Steel Dynamics" },
  { symbol: "STE", name: "Steris" },
  { symbol: "SYK", name: "Stryker Corporation" },
  { symbol: "SMCI", name: "Supermicro" },
  { symbol: "SYF", name: "Synchrony Financial" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "SYY", name: "Sysco" },
  { symbol: "TMUS", name: "T-Mobile US" },
  { symbol: "TROW", name: "T. Rowe Price" },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "TPR", name: "Tapestry, Inc." },
  { symbol: "TRGP", name: "Targa Resources" },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "TEL", name: "TE Connectivity" },
  { symbol: "TDY", name: "Teledyne Technologies" },
  { symbol: "TFX", name: "Teleflex" },
  { symbol: "TER", name: "Teradyne" },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "TPL", name: "Texas Pacific Land Corporation" },
  { symbol: "TXT", name: "Textron" },
  { symbol: "TMO", name: "Thermo Fisher Scientific" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "TSCO", name: "Tractor Supply" },
  { symbol: "TT", name: "Trane Technologies" },
  { symbol: "TDG", name: "TransDigm Group" },
  { symbol: "TRV", name: "Travelers Companies (The)" },
  { symbol: "TRMB", name: "Trimble Inc." },
  { symbol: "TFC", name: "Truist Financial" },
  { symbol: "TYL", name: "Tyler Technologies" },
  { symbol: "TSN", name: "Tyson Foods" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "ULTA", name: "Ulta Beauty" },
  { symbol: "UNP", name: "Union Pacific Corporation" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "URI", name: "United Rentals" },
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "UHS", name: "Universal Health Services" },
  { symbol: "VLO", name: "Valero Energy" },
  { symbol: "VTR", name: "Ventas" },
  { symbol: "VLTO", name: "Veralto" },
  { symbol: "VRSN", name: "Verisign" },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals" },
  { symbol: "VTRS", name: "Viatris" },
  { symbol: "VICI", name: "Vici Properties" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VST", name: "Vistra Corp." },
  { symbol: "VMC", name: "Vulcan Materials Company" },
  { symbol: "WRB", name: "W. R. Berkley Corporation" },
  { symbol: "GWW", name: "W. W. Grainger" },
  { symbol: "WAB", name: "Wabtec" },
  { symbol: "WBA", name: "Walgreens Boots Alliance" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "DIS", name: "Walt Disney Company" },
  { symbol: "WBD", name: "Warner Bros. Discovery" },
  { symbol: "WM", name: "Waste Management" },
  { symbol: "WAT", name: "Waters Corporation" },
  { symbol: "WEC", name: "WEC Energy Group" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "WELL", name: "Welltower" },
  { symbol: "WST", name: "West Pharmaceutical Services" },
  { symbol: "WDC", name: "Western Digital" },
  { symbol: "WY", name: "Weyerhaeuser" },
  { symbol: "WMB", name: "Williams Companies" },
  { symbol: "WTW", name: "Willis Towers Watson" },
  { symbol: "WYNN", name: "Wynn Resorts" },
  { symbol: "XEL", name: "Xcel Energy" },
  { symbol: "XYL", name: "Xylem Inc." },
  { symbol: "YUM", name: "Yum! Brands" },
  { symbol: "ZBRA", name: "Zebra Technologies" },
  { symbol: "ZBH", name: "Zimmer Biomet" },
  { symbol: "ZTS", name: "Zoetis" },
  {symbol: "IBM", name: "International Business Machines Corporation"},
  { symbol: "000001.SZ", name: "平安银行" },
  { symbol: "000002.SZ", name: "万科A" },
  { symbol: "000063.SZ", name: "中兴通讯" },
  { symbol: "000100.SZ", name: "TCL科技" },
  { symbol: "000157.SZ", name: "中联重科" },
  { symbol: "000166.SZ", name: "申万宏源" },
  { symbol: "000301.SZ", name: "东方盛虹" },
  { symbol: "000333.SZ", name: "美的集团" },
  { symbol: "000338.SZ", name: "潍柴动力" },
  { symbol: "000408.SZ", name: "藏格矿业" },
  { symbol: "000425.SZ", name: "徐工机械" },
  { symbol: "000538.SZ", name: "云南白药" },
  { symbol: "000568.SZ", name: "泸州老窖" },
  { symbol: "000596.SZ", name: "古井贡酒" },
  { symbol: "000617.SZ", name: "中油资本" },
  { symbol: "000625.SZ", name: "长安汽车" },
  { symbol: "000651.SZ", name: "格力电器" },
  { symbol: "000661.SZ", name: "长春高新" },
  { symbol: "000708.SZ", name: "中信特钢" },
  { symbol: "000725.SZ", name: "京东方A" },
  { symbol: "000733.SZ", name: "振华科技" },
  { symbol: "000768.SZ", name: "中航西飞" },
  { symbol: "000776.SZ", name: "广发证券" },
  { symbol: "000786.SZ", name: "北新建材" },
  { symbol: "000792.SZ", name: "盐湖股份" },
  { symbol: "000800.SZ", name: "一汽解放" },
  { symbol: "000807.SZ", name: "云铝股份" },
  { symbol: "000858.SZ", name: "五 粮 液" },
  { symbol: "000876.SZ", name: "新 希 望" },
  { symbol: "000895.SZ", name: "双汇发展" },
  { symbol: "000938.SZ", name: "紫光股份" },
  { symbol: "000963.SZ", name: "华东医药" },
  { symbol: "000977.SZ", name: "浪潮信息" },
  { symbol: "000983.SZ", name: "山西焦煤" },
  { symbol: "000999.SZ", name: "华润三九" },
  { symbol: "001289.SZ", name: "龙源电力" },
  { symbol: "001965.SZ", name: "招商公路" },
  { symbol: "001979.SZ", name: "招商蛇口" },
  { symbol: "002001.SZ", name: "新和成" },
  { symbol: "002007.SZ", name: "华兰生物" },
  { symbol: "002027.SZ", name: "分众传媒" },
  { symbol: "002049.SZ", name: "紫光国微" },
  { symbol: "002050.SZ", name: "三花智控" },
  { symbol: "002074.SZ", name: "国轩高科" },
  { symbol: "002129.SZ", name: "TCL中环" },
  { symbol: "002142.SZ", name: "宁波银行" },
  { symbol: "002179.SZ", name: "中航光电" },
  { symbol: "002180.SZ", name: "纳思达" },
  { symbol: "002230.SZ", name: "科大讯飞" },
  { symbol: "002236.SZ", name: "大华股份" },
  { symbol: "002241.SZ", name: "歌尔股份" },
  { symbol: "002252.SZ", name: "上海莱士" },
  { symbol: "002271.SZ", name: "东方雨虹" },
  { symbol: "002304.SZ", name: "洋河股份" },
  { symbol: "002311.SZ", name: "海大集团" },
  { symbol: "002352.SZ", name: "顺丰控股" },
  { symbol: "002371.SZ", name: "北方华创" },
  { symbol: "002410.SZ", name: "广联达" },
  { symbol: "002415.SZ", name: "海康威视" },
  { symbol: "002459.SZ", name: "晶澳科技" },
  { symbol: "002460.SZ", name: "赣锋锂业" },
  { symbol: "002466.SZ", name: "天齐锂业" },
  { symbol: "002475.SZ", name: "立讯精密" },
  { symbol: "002493.SZ", name: "荣盛石化" },
  { symbol: "002555.SZ", name: "三七互娱" },
  { symbol: "002594.SZ", name: "比亚迪" },
  { symbol: "002601.SZ", name: "龙佰集团" },
  { symbol: "002603.SZ", name: "以岭药业" },
  { symbol: "002648.SZ", name: "卫星化学" },
  { symbol: "002709.SZ", name: "天赐材料" },
  { symbol: "002714.SZ", name: "牧原股份" },
  { symbol: "002736.SZ", name: "国信证券" },
  { symbol: "002812.SZ", name: "恩捷股份" },
  { symbol: "002821.SZ", name: "凯莱英" },
  { symbol: "002841.SZ", name: "视源股份" },
  { symbol: "002916.SZ", name: "深南电路" },
  { symbol: "002920.SZ", name: "德赛西威" },
  { symbol: "002938.SZ", name: "鹏鼎控股" },
  { symbol: "003816.SZ", name: "中国广核" },
  { symbol: "300014.SZ", name: "亿纬锂能" },
  { symbol: "300015.SZ", name: "爱尔眼科" },
  { symbol: "300033.SZ", name: "同花顺" },
  { symbol: "300059.SZ", name: "东方财富" },
  { symbol: "300122.SZ", name: "智飞生物" },
  { symbol: "300124.SZ", name: "汇川技术" },
  { symbol: "300142.SZ", name: "沃森生物" },
  { symbol: "300223.SZ", name: "北京君正" },
  { symbol: "300274.SZ", name: "阳光电源" },
  { symbol: "300308.SZ", name: "中际旭创" },
  { symbol: "300316.SZ", name: "晶盛机电" },
  { symbol: "300347.SZ", name: "泰格医药" },
  { symbol: "300408.SZ", name: "三环集团" },
  { symbol: "300413.SZ", name: "芒果超媒" },
  { symbol: "300418.SZ", name: "昆仑万维" },
  { symbol: "300433.SZ", name: "蓝思科技" },
  { symbol: "300442.SZ", name: "润泽科技" },
  { symbol: "300450.SZ", name: "先导智能" },
  { symbol: "300454.SZ", name: "深信服" },
  { symbol: "300496.SZ", name: "中科创达" },
  { symbol: "300498.SZ", name: "温氏股份" },
  { symbol: "300628.SZ", name: "亿联网络" },
  { symbol: "300661.SZ", name: "圣邦股份" },
  { symbol: "300750.SZ", name: "宁德时代" },
  { symbol: "300751.SZ", name: "迈为股份" },
  { symbol: "300759.SZ", name: "康龙化成" },
  { symbol: "300760.SZ", name: "迈瑞医疗" },
  { symbol: "300782.SZ", name: "卓胜微" },
  { symbol: "300832.SZ", name: "新产业" },
  { symbol: "300896.SZ", name: "爱美客" },
  { symbol: "300919.SZ", name: "中伟股份" },
  { symbol: "300957.SZ", name: "贝泰妮" },
  { symbol: "300979.SZ", name: "华利集团" },
  { symbol: "300999.SZ", name: "金龙鱼" },
  { symbol: "301269.SZ", name: "华大九天" },
  { symbol: "600000.SS", name: "浦发银行" },
  { symbol: "600009.SS", name: "上海机场" },
  { symbol: "600010.SS", name: "包钢股份" },
  { symbol: "600011.SS", name: "华能国际" },
  { symbol: "600015.SS", name: "华夏银行" },
  { symbol: "600016.SS", name: "民生银行" },
  { symbol: "600018.SS", name: "上港集团" },
  { symbol: "600019.SS", name: "宝钢股份" },
  { symbol: "600023.SS", name: "浙能电力" },
  { symbol: "600025.SS", name: "华能水电" },
  { symbol: "600026.SS", name: "中远海能" },
  { symbol: "600027.SS", name: "华电国际" },
  { symbol: "600028.SS", name: "中国石化" },
  { symbol: "600029.SS", name: "南方航空" },
  { symbol: "600030.SS", name: "中信证券" },
  { symbol: "600031.SS", name: "三一重工" },
  { symbol: "600036.SS", name: "招商银行" },
  { symbol: "600039.SS", name: "四川路桥" },
  { symbol: "600048.SS", name: "保利发展" },
  { symbol: "600050.SS", name: "中国联通" },
  { symbol: "600061.SS", name: "国投资本" },
  { symbol: "600085.SS", name: "同仁堂" },
  { symbol: "600089.SS", name: "特变电工" },
  { symbol: "600104.SS", name: "上汽集团" },
  { symbol: "600111.SS", name: "北方稀土" },
  { symbol: "600115.SS", name: "中国东航" },
  { symbol: "600132.SS", name: "重庆啤酒" },
  { symbol: "600150.SS", name: "中国船舶" },
  { symbol: "600161.SS", name: "天坛生物" },
  { symbol: "600176.SS", name: "中国巨石" },
  { symbol: "600183.SS", name: "生益科技" },
  { symbol: "600188.SS", name: "兖矿能源" },
  { symbol: "600196.SS", name: "复星医药" },
  { symbol: "600219.SS", name: "南山铝业" },
  { symbol: "600233.SS", name: "圆通速递" },
  { symbol: "600276.SS", name: "恒瑞医药" },
  { symbol: "600309.SS", name: "万华化学" },
  { symbol: "600332.SS", name: "白云山" },
  { symbol: "600346.SS", name: "恒力石化" },
  { symbol: "600362.SS", name: "江西铜业" },
  { symbol: "600372.SS", name: "中航机载" },
  { symbol: "600406.SS", name: "国电南瑞" },
  { symbol: "600415.SS", name: "小商品城" },
  { symbol: "600426.SS", name: "华鲁恒升" },
  { symbol: "600436.SS", name: "片仔癀" },
  { symbol: "600438.SS", name: "通威股份" },
  { symbol: "600460.SS", name: "士兰微" },
  { symbol: "600489.SS", name: "中金黄金" },
  { symbol: "600515.SS", name: "海南机场" },
  { symbol: "600519.SS", name: "贵州茅台" },
  { symbol: "600547.SS", name: "山东黄金" },
  { symbol: "600570.SS", name: "恒生电子" },
  { symbol: "600584.SS", name: "长电科技" },
  { symbol: "600585.SS", name: "海螺水泥" },
  { symbol: "600588.SS", name: "用友网络" },
  { symbol: "600600.SS", name: "青岛啤酒" },
  { symbol: "600660.SS", name: "福耀玻璃" },
  { symbol: "600674.SS", name: "川投能源" },
  { symbol: "600690.SS", name: "海尔智家" },
  { symbol: "600732.SS", name: "爱旭股份" },
  { symbol: "600741.SS", name: "华域汽车" },
  { symbol: "600745.SS", name: "闻泰科技" },
  { symbol: "600760.SS", name: "中航沈飞" },
  { symbol: "600795.SS", name: "国电电力" },
  { symbol: "600803.SS", name: "新奥股份" },
  { symbol: "600809.SS", name: "山西汾酒" },
  { symbol: "600837.SS", name: "海通证券" },
  { symbol: "600845.SS", name: "宝信软件" },
  { symbol: "600875.SS", name: "东方电气" },
  { symbol: "600886.SS", name: "国投电力" },
  { symbol: "600887.SS", name: "伊利股份" },
  { symbol: "600893.SS", name: "航发动力" },
  { symbol: "600900.SS", name: "长江电力" },
  { symbol: "600905.SS", name: "三峡能源" },
  { symbol: "600918.SS", name: "中泰证券" },
  { symbol: "600919.SS", name: "江苏银行" },
  { symbol: "600926.SS", name: "杭州银行" },
  { symbol: "600938.SS", name: "中国海油" },
  { symbol: "600941.SS", name: "中国移动" },
  { symbol: "600958.SS", name: "东方证券" },
  { symbol: "600989.SS", name: "宝丰能源" },
  { symbol: "600999.SS", name: "招商证券" },
  { symbol: "601006.SS", name: "大秦铁路" },
  { symbol: "601009.SS", name: "南京银行" },
  { symbol: "601012.SS", name: "隆基绿能" },
  { symbol: "601021.SS", name: "春秋航空" },
  { symbol: "601059.SS", name: "信达证券" },
  { symbol: "601066.SS", name: "中信建投" },
  { symbol: "601088.SS", name: "中国神华" },
  { symbol: "601100.SS", name: "恒立液压" },
  { symbol: "601111.SS", name: "中国国航" },
  { symbol: "601117.SS", name: "中国化学" },
  { symbol: "601138.SS", name: "工业富联" },
  { symbol: "601166.SS", name: "兴业银行" },
  { symbol: "601169.SS", name: "北京银行" },
  { symbol: "601186.SS", name: "中国铁建" },
  { symbol: "601211.SS", name: "国泰君安" },
  { symbol: "601225.SS", name: "陕西煤业" },
  { symbol: "601229.SS", name: "上海银行" },
  { symbol: "601236.SS", name: "红塔证券" },
  { symbol: "601238.SS", name: "广汽集团" },
  { symbol: "601288.SS", name: "农业银行" },
  { symbol: "601318.SS", name: "中国平安" },
  { symbol: "601319.SS", name: "中国人保" },
  { symbol: "601328.SS", name: "交通银行" },
  { symbol: "601336.SS", name: "新华保险" },
  { symbol: "601360.SS", name: "三六零" },
  { symbol: "601377.SS", name: "兴业证券" },
  { symbol: "601390.SS", name: "中国中铁" },
  { symbol: "601398.SS", name: "工商银行" },
  { symbol: "601600.SS", name: "中国铝业" },
  { symbol: "601601.SS", name: "中国太保" },
  { symbol: "601607.SS", name: "上海医药" },
  { symbol: "601618.SS", name: "中国中冶" },
  { symbol: "601628.SS", name: "中国人寿" },
  { symbol: "601633.SS", name: "长城汽车" },
  { symbol: "601658.SS", name: "邮储银行" },
  { symbol: "601668.SS", name: "中国建筑" },
  { symbol: "601669.SS", name: "中国电建" },
  { symbol: "601688.SS", name: "华泰证券" },
  { symbol: "601689.SS", name: "拓普集团" },
  { symbol: "601698.SS", name: "中国卫通" },
  { symbol: "601699.SS", name: "潞安环能" },
  { symbol: "601728.SS", name: "中国电信" },
  { symbol: "601766.SS", name: "中国中车" },
  { symbol: "601788.SS", name: "光大证券" },
  { symbol: "601799.SS", name: "星宇股份" },
  { symbol: "601800.SS", name: "中国交建" },
  { symbol: "601808.SS", name: "中海油服" },
  { symbol: "601816.SS", name: "京沪高铁" },
  { symbol: "601818.SS", name: "光大银行" },
  { symbol: "601838.SS", name: "成都银行" },
  { symbol: "601857.SS", name: "中国石油" },
  { symbol: "601865.SS", name: "福莱特" },
  { symbol: "601868.SS", name: "中国能建" },
  { symbol: "601872.SS", name: "招商轮船" },
  { symbol: "601877.SS", name: "正泰电器" },
  { symbol: "601878.SS", name: "浙商证券" },
  { symbol: "601881.SS", name: "中国银河" },
  { symbol: "601888.SS", name: "中国中免" },
  { symbol: "601898.SS", name: "中煤能源" },
  { symbol: "601899.SS", name: "紫金矿业" },
  { symbol: "601901.SS", name: "方正证券" },
  { symbol: "601916.SS", name: "浙商银行" },
  { symbol: "601919.SS", name: "中远海控" },
  { symbol: "601939.SS", name: "建设银行" },
  { symbol: "601985.SS", name: "中国核电" },
  { symbol: "601988.SS", name: "中国银行" },
  { symbol: "601989.SS", name: "中国重工" },
  { symbol: "601995.SS", name: "中金公司" },
  { symbol: "601998.SS", name: "中信银行" },
  { symbol: "603019.SS", name: "中科曙光" },
  { symbol: "603195.SS", name: "公牛集团" },
  { symbol: "603259.SS", name: "药明康德" },
  { symbol: "603260.SS", name: "合盛硅业" },
  { symbol: "603288.SS", name: "海天味业" },
  { symbol: "603296.SS", name: "华勤技术" },
  { symbol: "603369.SS", name: "今世缘" },
  { symbol: "603392.SS", name: "万泰生物" },
  { symbol: "603501.SS", name: "韦尔股份" },
  { symbol: "603659.SS", name: "璞泰来" },
  { symbol: "603799.SS", name: "华友钴业" },
  { symbol: "603806.SS", name: "福斯特" },
  { symbol: "603833.SS", name: "欧派家居" },
  { symbol: "603899.SS", name: "晨光股份" },
  { symbol: "603986.SS", name: "兆易创新" },
  { symbol: "603993.SS", name: "洛阳钼业" },
  { symbol: "605117.SS", name: "德业股份" },
  { symbol: "605499.SS", name: "东鹏饮料" },
  { symbol: "0001.HK", name: "CKH HOLDINGS" },
  { symbol: "0002.HK", name: "CLP HOLDINGS" },
  { symbol: "0003.HK", name: "HK & CHINA GAS" },
  { symbol: "0005.HK", name: "HSBC HOLDINGS" },
  { symbol: "0006.HK", name: "POWER ASSETS" },
  { symbol: "0011.HK", name: "HANG SENG BANK" },
  { symbol: "0012.HK", name: "HENDERSON LAND" },
  { symbol: "0016.HK", name: "SHK PPT" },
  { symbol: "0017.HK", name: "NEW WORLD DEV" },
  { symbol: "0027.HK", name: "GALAXY ENT" },
  { symbol: "0066.HK", name: "MTR CORPORATION" },
  { symbol: "0101.HK", name: "HANG LUNG PPT" },
  { symbol: "0175.HK", name: "GEELY AUTO" },
  { symbol: "0241.HK", name: "ALI HEALTH" },
  { symbol: "0267.HK", name: "CITIC" },
  { symbol: "0285.HK", name: "BYD ELECTRONIC" },
  { symbol: "0288.HK", name: "WH GROUP" },
  { symbol: "0291.HK", name: "CHINA RES BEER" },
  { symbol: "0316.HK", name: "OOIL" },
  { symbol: "0322.HK", name: "TINGYI" },
  { symbol: "0386.HK", name: "SINOPEC CORP" },
  { symbol: "0388.HK", name: "HKEX" },
  { symbol: "0669.HK", name: "TECHTRONIC IND" },
  { symbol: "0688.HK", name: "CHINA OVERSEAS" },
  { symbol: "0700.HK", name: "TENCENT" },
  { symbol: "0762.HK", name: "CHINA UNICOM" },
  { symbol: "0823.HK", name: "LINK REIT" },
  { symbol: "0836.HK", name: "CHINA RES POWER" },
  { symbol: "0857.HK", name: "PETROCHINA" },
  { symbol: "0868.HK", name: "XINYI GLASS" },
  { symbol: "0881.HK", name: "ZHONGSHENG HLDG" },
  { symbol: "0883.HK", name: "CNOOC" },
  { symbol: "0939.HK", name: "CCB" },
  { symbol: "0941.HK", name: "CHINA MOBILE" },
  { symbol: "0960.HK", name: "LONGFOR GROUP" },
  { symbol: "0968.HK", name: "XINYI SOLAR" },
  { symbol: "0981.HK", name: "SMIC" },
  { symbol: "0992.HK", name: "LENOVO GROUP" },
  { symbol: "1038.HK", name: "CKI HOLDINGS" },
  { symbol: "1044.HK", name: "HENGAN INT'L" },
  { symbol: "1088.HK", name: "CHINA SHENHUA" },
  { symbol: "1093.HK", name: "CSPC PHARMA" },
  { symbol: "1099.HK", name: "SINOPHARM" },
  { symbol: "1109.HK", name: "CHINA RES LAND" },
  { symbol: "1113.HK", name: "CK ASSET" },
  { symbol: "1177.HK", name: "SINO BIOPHARM" },
  { symbol: "1209.HK", name: "CHINA RES MIXC" },
  { symbol: "1211.HK", name: "BYD COMPANY" },
  { symbol: "1299.HK", name: "AIA" },
  { symbol: "1378.HK", name: "CHINAHONGQIAO" },
  { symbol: "1398.HK", name: "ICBC" },
  { symbol: "1810.HK", name: "XIAOMI-W" },
  { symbol: "1876.HK", name: "BUD APAC" },
  { symbol: "1928.HK", name: "SANDS CHINA LTD" },
  { symbol: "1929.HK", name: "CHOW TAI FOOK" },
  { symbol: "1997.HK", name: "WHARF REIC" },
  { symbol: "2015.HK", name: "LI AUTO-W" },
  { symbol: "2020.HK", name: "ANTA SPORTS" },
  { symbol: "2269.HK", name: "WUXI BIO" },
  { symbol: "2313.HK", name: "SHENZHOU INTL" },
  { symbol: "2318.HK", name: "PING AN" },
  { symbol: "2319.HK", name: "MENGNIU DAIRY" },
  { symbol: "2331.HK", name: "LI NING" },
  { symbol: "2359.HK", name: "WUXI APPTEC" },
  { symbol: "2382.HK", name: "SUNNY OPTICAL" },
  { symbol: "2388.HK", name: "BOC HONG KONG" },
  { symbol: "2628.HK", name: "CHINA LIFE" },
  { symbol: "2688.HK", name: "ENN ENERGY" },
  { symbol: "2899.HK", name: "ZIJIN MINING" },
  { symbol: "3690.HK", name: "MEITUAN-W" },
  { symbol: "3692.HK", name: "HANSOH PHARMA" },
  { symbol: "3968.HK", name: "CM BANK" },
  { symbol: "3988.HK", name: "BANK OF CHINA" },
  { symbol: "6618.HK", name: "JD HEALTH" },
  { symbol: "6690.HK", name: "HAIER SMARTHOME" },
  { symbol: "6862.HK", name: "HAIDILAO" },
  { symbol: "9618.HK", name: "JD-SW" },
  { symbol: "9633.HK", name: "NONGFU SPRING" },
  { symbol: "9888.HK", name: "BIDU-SW" },
  { symbol: "9961.HK", name: "TRIP.COM-S" },
  { symbol: "9988.HK", name: "BABA-W" },
  { symbol: "9999.HK", name: "NTES-S" },
];
